Add collection entry for road and  building detection data
sentinel-hub/collections pull request #137
Opened 2024-05-10 13:09 UTC by Dorothyrono

Add new data product + sandbox data pages for Roads & Buildings

2024-05-13 07:00 UTC, zansinergise requested changes
What's the status with the map - are the polygons being created?

Note: I would wait with merging this until we get a final comment regarding the colors which should be used in the evalscripts, since you will likely have to change the highlight photos

Otherwise looks good 👍

2024-05-13 07:16 UTC, Dorothyrono commented on collections/road-and-building-detection.yaml
> +        Values: " "
> What's the status with the map - are the polygons being created?

expected today.  
Agree,  will wait with the merging

2024-05-15 21:51 UTC, zcernigoj commented
> What's the status with the map - are the polygons being created?

They are now.

2024-05-16 07:08 UTC, zansinergise commented on collections/road-and-building-detection.yaml
> +        Values: " "
Looks like the colors will not change, so all good from my side 👍

2024-05-16 07:09 UTC, zansinergise approved these changes
Polygons were created, so map should be available now, good to go! 👍

2024-06-11 06:44 UTC, merged